#ifndef _LEXICAL_H_
#define _LEXICAL_H_

typedef enum _token_enum {
    ENDFILE = 0, 
    ERROR = 1,
    // Eey Word
    KW_ARRAY = 2,
    KW_BGGIN = 3,
    KW_CHAR = 4,
    KW_CONST = 5,
    KW_DO = 6,
    KW_DOWNTO = 7,
    KW_ELSE = 8,
    KW_END = 9,
    KW_FOR = 10,
    KW_FUNCTION = 11,
    KW_IF = 12,
    KW_INTEGER = 13,
    KW_OF = 14,
    KW_PROCEDURE = 15,
    KW_READ = 16,
    KW_REPEAT = 17,
    KW_THEN = 18,
    KW_TO = 19,
    KW_UNTIL = 20,
    KW_VAR = 21,
    KW_WRITE = 22,
    //Multi-Character Token
    MC_ID = 23,
    MC_CH = 24,
    MC_UNS = 25,
    MC_STR = 26,
    //Spacial Symbol as Token
    SS_PLUS = 27,
    SS_MINUS= 28,
    SS_STAR = 29,
    SS_OVER = 30,
    SS_EQU = 31,
    SS_LST = 32,
    SS_LEQ = 33,
    SS_GTT = 34,
    SS_GEQ = 35,
    SS_NEQ = 36,
    SS_COMMA = 37,
    SS_SEMI = 38,
	SS_ASGN = 39,
	SS_LPAR = 40,
    SS_RPAR = 41,
	SS_LBRA = 42,
	SS_RBRA = 43,
	SS_LBBR = 44,
	SS_RBBR = 45,
	SS_SQUO = 46,
	SS_DQUO = 47,
	SS_COLON = 48,
	SS_DOT = 49,
}token_t;
#endif